name: local-environment

networks:
  default:
    name: local-network

services:
  crud-api:
    container_name: local-crud-api
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        PROD_MODE: "false"
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personals
      POSTGRES_PORT: 5435

    volumes:
      - ./app:/app/app
    ports:
      - "8001:80"
