name: self-local-environment

services:
  postgres:
    container_name: DB
    image: postgres:13.9-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

