name: self-local-environment

services:
  postgres:
    container_name: DB
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # PGDATA: /var/lib/postgresql/data
    # volumes:
    #   - ./local_pgdata:/var/lib/postgresql/data

  # fastapi:
  #   container_name: FastAPI-BE
  #   build:
  #     context: .
  #     dockerfile: fastapi.Dockerfile
  #   command: bash -c 'while !</dev/tcp/postgres/5435; do sleep 5; done; uvicorn main:app --host 0.0.0.0 --port 8080 --reload'
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./.env
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_SERVER: ${POSTGRES_SERVER}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   volumes:
  #     - ./app:/app
  #   restart: always
  #   ports:
  #     - "8080:8080"
