name: self-local-environment

networks:
  default:
    name: local-network

services:
  crud-web:
    container_name: local-crud-web
    restart: always
    build:
      dockerfile: Dockerfile.local
      context: .
      args:
        BUILD_ENV: localhost
        TLS_FROM_NGINX: false
    ports:
      - 4001:4001