name: self-local-environment

networks:
  default:
    name: local-network

services:
  crud-web:
    container_name: local-crud-web
    restart: always
    build:
      dockerfile: .Dockerfile
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173
    labels:
      traefik.enable: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.http.middlewares.crud-web-cors.headers.accesscontrolallowcredentials: "true"
      traefik.http.middlewares.crud-web-cors.headers.accesscontrolallowheaders: "*"
      traefik.http.middlewares.crud-web-cors.headers.accesscontrolallowmethods: "*"
      traefik.http.middlewares.crud-web-cors.headers.accesscontrolalloworiginlist: "*"
      traefik.http.routers.crud-web-main.entrypoints: web
      traefik.http.routers.crud-web-main.middlewares: crud-web-cors
      traefik.http.routers.crud-web-main.rule: PathPrefix(`/`) && Host(`self.localhost`)
      traefik.http.services.crud-web-service.loadBalancer.server.scheme: http
      traefik.http.services.crud-web-service.loadBalancer.serversTransport: default@internal
